services:
  postgres:
    image: postgres:17-alpine
    container_name: nexcart-postgres
    environment:
      POSTGRES_DB: nexcart
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nexcart-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
    container_name: nexcart-user-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/nexcart
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - nexcart-network

volumes:
  postgres_data:
    driver: local

networks:
  nexcart-network:
    driver: bridge
